---
#########################################
#
# author : Gharios Damien
# date : 07-2020
# enterprise : Donow
#
#########################################
# Playbook Ansible called by GitHub Action (workflow).
# This playbook will pull GitHub repo containing a Docker.
# It pushes all configurations for NginX (+restarting service),
# Build and up docker container with a docker-compose.yml file.

- name: NginX configuration deploiement with Github + Docker-compose
  hosts: web
  remote_user: ec2-user
  become_method: sudo
  gather_facts: yes
  connection: ssh

  tasks:
   - include_vars: vars_conf.yml
   
   - name: GitHub repo import
     git: 
        repo: "{{ repo_github }}"
        dest: "{{ user_dir }}/"

   - name: Nginx configuration file add
     become: true
     template:
        src: templates/nginx.conf.j2
        dest: "{{ nginx_dir }}/{{ server_name }}.conf"
                
   - name: server line add in /etc/hosts
     become: true
     lineinfile:
        dest: /etc/hosts
        regexp: "{{ server_name }}"
        line: "127.0.0.1 {{ server_name }}"
  
   - name: Up & build docker-compose container
     docker_compose:
        project_src: "{{ user_dir }}/{{ docker_dir }}"
        state: present
        build: yes

   - name: Restart NginX service
     become: true
     service:
        name: nginx
        state: restarted
